const SUPABASE_URL='https://xjfneodxvhnwvedvjdtd.supabase.co';
const SUPABASE_KEY='sb_publishable_8n2QgppfFL3ylwwPTClvZQ_EBNgQl0K';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const KEY_STAFF='staffTracker.employees',KEY_ENTRIES='staffTracker.entries';
let employees=[],entries=[],historyPage=1,currentUser=null,realtimeChannel=null,signupMode=false;
const $=id=>document.getElementById(id),today=new Date();
$('date').value=today.toISOString().slice(0,10);$('month').value=today.toISOString().slice(0,7);
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function setSync(text,type=''){$('syncStatus').textContent=text;$('syncStatus').className='sync '+type}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hours(e){if(e.status!=='Î•ÏÎ³Î±ÏƒÎ¯Î±'||!e.start_time||!e.end_time)return 0;let [sh,sm]=e.start_time.split(':').map(Number),[eh,em]=e.end_time.split(':').map(Number),m=(eh*60+em)-(sh*60+sm);if(m<0)m+=1440;return m/60}
function formatHours(n){return (Math.round(n*100)/100).toLocaleString('el-GR',{maximumFractionDigits:2})}
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('el-GR')}
function pill(s){let c=s==='Î•ÏÎ³Î±ÏƒÎ¯Î±'?'work':s.includes('Î‘Î´Î¹ÎºÎ±Î¹Î¿Î»ÏŒÎ³Î·Ï„Î·')?'absent':'';return `<span class="pill ${c}">${esc(s)}</span>`}
function download(name,type,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function showApp(show){$('loginScreen').hidden=show;$('appShell').hidden=!show}

async function loadCloudData({offerMigration=false}={}){
  if(!currentUser)return;
  setSync('Î£Ï…Î³Ï‡ÏÎ¿Î½Î¹ÏƒÎ¼ÏŒÏ‚â€¦');
  const [staffResult,entryResult]=await Promise.all([
    db.from('employees').select('name').order('name'),
    db.from('entries').select('id,work_date,employee,status,start_time,end_time,notes,created_at').order('work_date',{ascending:false})
  ]);
  if(staffResult.error||entryResult.error){setSync('Î£Ï†Î¬Î»Î¼Î± ÏƒÏÎ½Î´ÎµÏƒÎ·Ï‚','error');throw staffResult.error||entryResult.error}
  employees=staffResult.data.map(x=>x.name);
  entries=entryResult.data;
  renderEmployees();renderRecent();renderSummary();setSync('Î£Ï…Î³Ï‡ÏÎ¿Î½Î¯ÏƒÏ„Î·ÎºÎµ','ok');
  if(offerMigration&&employees.length===0&&entries.length===0)await offerLocalMigration();
}
async function offerLocalMigration(){
  let localEmployees=JSON.parse(localStorage.getItem(KEY_STAFF)||'[]');
  let localEntries=JSON.parse(localStorage.getItem(KEY_ENTRIES)||'[]');
  if(!localEmployees.length&&!localEntries.length)return;
  if(!confirm(`Î’ÏÎ­Î¸Î·ÎºÎ±Î½ ${localEntries.length} Ï€Î±Î»Î¹Î­Ï‚ ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚ ÏƒÎµ Î±Ï…Ï„ÏŒÎ½ Ï„Î¿Î½ browser. ÎÎ± Î¼ÎµÏ„Î±Ï†ÎµÏÎ¸Î¿ÏÎ½ Ï„ÏŽÏÎ± ÏƒÏ„Î¿ cloud;`))return;
  setSync('ÎœÎµÏ„Î±Ï†Î¿ÏÎ¬ Î´ÎµÎ´Î¿Î¼Î­Î½Ï‰Î½â€¦');
  if(localEmployees.length){let {error}=await db.from('employees').upsert(localEmployees.map(name=>({user_id:currentUser.id,name})),{onConflict:'user_id,name'});if(error)throw error}
  if(localEntries.length){let rows=localEntries.map((e,i)=>({id:`legacy-${currentUser.id.slice(0,8)}-${e.id||Date.now()+'-'+i}`,user_id:currentUser.id,work_date:e.date,employee:e.employee,status:e.status,start_time:e.start||null,end_time:e.end||null,notes:e.notes||''}));let {error}=await db.from('entries').upsert(rows);if(error)throw error}
  await loadCloudData();toast('Î¤Î± Ï€Î±Î»Î¹Î¬ Î´ÎµÎ´Î¿Î¼Î­Î½Î± Î¼ÎµÏ„Î±Ï†Î­ÏÎ¸Î·ÎºÎ±Î½ ÏƒÏ„Î¿ cloud')
}
function subscribeRealtime(){if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=db.channel(`staff-${currentUser.id}`).on('postgres_changes',{event:'*',schema:'public',table:'employees',filter:`user_id=eq.${currentUser.id}`},()=>loadCloudData()).on('postgres_changes',{event:'*',schema:'public',table:'entries',filter:`user_id=eq.${currentUser.id}`},()=>loadCloudData()).subscribe()}
async function enterApp(user){currentUser=user;$('accountEmail').textContent=user.email||'';showApp(true);await loadCloudData({offerMigration:true});subscribeRealtime()}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';let email=$('loginEmail').value.trim(),password=$('loginPassword').value;try{let result=signupMode?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signupMode&&!result.data.session){$('loginError').style.color='var(--green)';$('loginError').textContent='Î•Î»Î­Î³Î¾Ï„Îµ Ï„Î¿ email ÏƒÎ±Ï‚ Î³Î¹Î± ÎµÏ€Î¹Î²ÎµÎ²Î±Î¯Ï‰ÏƒÎ·.';return}if(result.data.user)await enterApp(result.data.user)}catch(err){$('loginError').style.color='var(--red)';$('loginError').textContent=err.message==='Invalid login credentials'?'Î›Î¬Î¸Î¿Ï‚ email Î® ÎºÏ‰Î´Î¹ÎºÏŒÏ‚.':err.message}});
$('showSignup').onclick=()=>{signupMode=!signupMode;$('loginForm').querySelector('button[type="submit"]').textContent=signupMode?'Î”Î·Î¼Î¹Î¿Ï…ÏÎ³Î¯Î± Î»Î¿Î³Î±ÏÎ¹Î±ÏƒÎ¼Î¿Ï':'Î£ÏÎ½Î´ÎµÏƒÎ·';$('showSignup').textContent=signupMode?'ÎˆÏ‡Ï‰ Î®Î´Î· Î»Î¿Î³Î±ÏÎ¹Î±ÏƒÎ¼ÏŒ':'Î”Î·Î¼Î¹Î¿Ï…ÏÎ³Î¯Î± Ï€ÏÏŽÏ„Î¿Ï… Î»Î¿Î³Î±ÏÎ¹Î±ÏƒÎ¼Î¿Ï';$('loginError').textContent=''};
$('logout').onclick=async()=>{if(realtimeChannel)await db.removeChannel(realtimeChannel);await db.auth.signOut();currentUser=null;employees=[];entries=[];showApp(false);$('loginForm').reset()};

function renderEmployees(){let opts=employees.length?employees.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join(''):'<option value="">Î ÏÎ¿ÏƒÎ¸Î­ÏƒÏ„Îµ Ï€ÏÏŽÏ„Î± ÎµÏÎ³Î±Î¶ÏŒÎ¼ÎµÎ½Î¿</option>';let selectedEmployee=$('employee').value,selectedSummary=$('summaryEmployee').value,oldHistory=$('historyEmployee').value;$('employee').innerHTML=opts;$('summaryEmployee').innerHTML=opts;$('historyEmployee').innerHTML='<option value="">ÎŒÎ»Î¿ Ï„Î¿ Ï€ÏÎ¿ÏƒÏ‰Ï€Î¹ÎºÏŒ</option>'+opts;if(employees.includes(selectedEmployee))$('employee').value=selectedEmployee;if(employees.includes(selectedSummary))$('summaryEmployee').value=selectedSummary;if(employees.includes(oldHistory))$('historyEmployee').value=oldHistory;$('staffRows').innerHTML=employees.length?employees.map((n,i)=>`<tr><td>${esc(n)}</td><td><button class="btn danger small" onclick="removeEmployee(${i})">Î”Î¹Î±Î³ÏÎ±Ï†Î®</button></td></tr>`).join(''):'<tr><td colspan="2" class="empty">Î”ÎµÎ½ Î­Ï‡ÎµÎ¹ Ï€ÏÎ¿ÏƒÏ„ÎµÎ¸ÎµÎ¯ Ï€ÏÎ¿ÏƒÏ‰Ï€Î¹ÎºÏŒ.</td></tr>';renderSummary()}
function renderRecent(){let emp=$('historyEmployee').value,month=$('historyMonth').value;let list=[...entries].filter(e=>(!emp||e.employee===emp)&&(!month||e.work_date.startsWith(month))).sort((a,b)=>b.work_date.localeCompare(a.work_date));let pageSize=25,pages=Math.max(1,Math.ceil(list.length/pageSize));historyPage=Math.min(historyPage,pages);let shown=list.slice((historyPage-1)*pageSize,historyPage*pageSize);$('recentRows').innerHTML=shown.length?shown.map(e=>`<tr><td>${formatDate(e.work_date)}</td><td>${esc(e.employee)}</td><td>${pill(e.status)}</td><td>${e.start_time&&e.end_time?e.start_time.slice(0,5)+'â€“'+e.end_time.slice(0,5):'â€”'}</td><td>${formatHours(hours(e))}</td><td>${esc(e.notes)||'â€”'}</td><td><button class="btn secondary small" onclick="editEntry('${e.id}')">Î‘Î»Î»Î±Î³Î®</button> <button class="btn danger small" onclick="deleteEntry('${e.id}')">Î”Î¹Î±Î³ÏÎ±Ï†Î®</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Î”ÎµÎ½ Ï…Ï€Î¬ÏÏ‡Î¿Ï…Î½ ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚.</td></tr>';$('pageInfo').textContent=`Î£ÎµÎ»Î¯Î´Î± ${historyPage} Î±Ï€ÏŒ ${pages} Â· ${list.length} ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚`;$('prevPage').disabled=historyPage<=1;$('nextPage').disabled=historyPage>=pages}
function renderSummary(){let month=$('month').value,emp=$('summaryEmployee').value,list=entries.filter(e=>e.employee===emp&&e.work_date.startsWith(month));let counts={};list.forEach(e=>counts[e.status]=(counts[e.status]||0)+1);$('workedDays').textContent=counts['Î•ÏÎ³Î±ÏƒÎ¯Î±']||0;$('workedHours').textContent=formatHours(list.reduce((s,e)=>s+hours(e),0));let nonwork=list.filter(e=>e.status!=='Î•ÏÎ³Î±ÏƒÎ¯Î±').length;$('notWorked').textContent=nonwork;$('unexcused').textContent=counts['Î‘Î´Î¹ÎºÎ±Î¹Î¿Î»ÏŒÎ³Î·Ï„Î· Î±Ï€Î¿Ï…ÏƒÎ¯Î±']||0;let cats=['Î¡ÎµÏ€ÏŒ','Î†Î´ÎµÎ¹Î±','Î‘Î½Î±ÏÏÏ‰Ï„Î¹ÎºÎ®','Î”Î¹ÎºÎ±Î¹Î¿Î»Î¿Î³Î·Î¼Î­Î½Î· Î±Ï€Î¿Ï…ÏƒÎ¯Î±','Î‘Î´Î¹ÎºÎ±Î¹Î¿Î»ÏŒÎ³Î·Ï„Î· Î±Ï€Î¿Ï…ÏƒÎ¯Î±'];$('breakdown').innerHTML=cats.map(c=>`<tr><td>${pill(c)}</td><td>${counts[c]||0}</td></tr>`).join('')+`<tr><th>Î£ÏÎ½Î¿Î»Î¿ Î·Î¼ÎµÏÏŽÎ½ Ï€Î¿Ï… Î´ÎµÎ½ ÎµÏÎ³Î¬ÏƒÏ„Î·ÎºÎµ</th><th>${nonwork}</th></tr>`;$('monthRows').innerHTML=list.length?[...list].sort((a,b)=>a.work_date.localeCompare(b.work_date)).map(e=>`<tr><td>${formatDate(e.work_date)}</td><td>${pill(e.status)}</td><td>${e.start_time&&e.end_time?e.start_time.slice(0,5)+'â€“'+e.end_time.slice(0,5):'â€”'}</td><td>${formatHours(hours(e))}</td><td>${esc(e.notes)||'â€”'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Î”ÎµÎ½ Ï…Ï€Î¬ÏÏ‡Î¿Ï…Î½ ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚ Î³Î¹Î± Î±Ï…Ï„Î® Ï„Î·Î½ ÎµÏ€Î¹Î»Î¿Î³Î®.</td></tr>'}
function resetForm(){$('entryForm').reset();$('date').value=today.toISOString().slice(0,10);$('editId').value='';$('formTitle').textContent='ÎšÎ±Ï„Î±Ï‡ÏŽÏÎ¹ÏƒÎ· Î·Î¼Î­ÏÎ±Ï‚';$('cancelEdit').hidden=true;toggleTimes()}
function toggleTimes(){let show=$('status').value==='Î•ÏÎ³Î±ÏƒÎ¯Î±';document.querySelectorAll('.work-time').forEach(x=>x.style.display=show?'block':'none');if(!show){$('start').value='';$('end').value=''}}

$('entryForm').addEventListener('submit',async e=>{e.preventDefault();if(!employees.length)return toast('Î ÏÎ¿ÏƒÎ¸Î­ÏƒÏ„Îµ Ï€ÏÏŽÏ„Î± Î­Î½Î±Î½ ÎµÏÎ³Î±Î¶ÏŒÎ¼ÎµÎ½Î¿');let id=$('editId').value||crypto.randomUUID(),row={id,user_id:currentUser.id,work_date:$('date').value,employee:$('employee').value,status:$('status').value,start_time:$('start').value||null,end_time:$('end').value||null,notes:$('notes').value.trim()};let duplicate=entries.find(x=>x.id!==id&&x.work_date===row.work_date&&x.employee===row.employee);if(duplicate&&!confirm('Î¥Ï€Î¬ÏÏ‡ÎµÎ¹ Î®Î´Î· ÎºÎ±Ï„Î±Ï‡ÏŽÏÎ¹ÏƒÎ· Î³Î¹Î± Î±Ï…Ï„ÏŒÎ½ Ï„Î¿Î½ ÎµÏÎ³Î±Î¶ÏŒÎ¼ÎµÎ½Î¿ ÎºÎ±Î¹ Ï„Î·Î½ Î·Î¼ÎµÏÎ¿Î¼Î·Î½Î¯Î±. ÎÎ± Ï€ÏÎ¿ÏƒÏ„ÎµÎ¸ÎµÎ¯ ÎºÎ±Î¹ Î´ÎµÏÏ„ÎµÏÎ·;'))return;setSync('Î‘Ï€Î¿Î¸Î®ÎºÎµÏ…ÏƒÎ·â€¦');let {error}=await db.from('entries').upsert(row);if(error){setSync('Î£Ï†Î¬Î»Î¼Î±','error');return toast('Î— Î±Ï€Î¿Î¸Î®ÎºÎµÏ…ÏƒÎ· Î±Ï€Î­Ï„Ï…Ï‡Îµ')}resetForm();await loadCloudData();toast('Î— ÎºÎ±Ï„Î±Ï‡ÏŽÏÎ¹ÏƒÎ· Î±Ï€Î¿Î¸Î·ÎºÎµÏÏ„Î·ÎºÎµ')});
$('staffForm').addEventListener('submit',async e=>{e.preventDefault();let name=$('newEmployee').value.trim();if(!name||employees.includes(name))return toast('Î¤Î¿ ÏŒÎ½Î¿Î¼Î± Ï…Ï€Î¬ÏÏ‡ÎµÎ¹ Î®Î´Î·');let {error}=await db.from('employees').insert({user_id:currentUser.id,name});if(error)return toast('Î— Ï€ÏÎ¿ÏƒÎ¸Î®ÎºÎ· Î±Ï€Î­Ï„Ï…Ï‡Îµ');$('newEmployee').value='';await loadCloudData();toast('ÎŸ ÎµÏÎ³Î±Î¶ÏŒÎ¼ÎµÎ½Î¿Ï‚ Ï€ÏÎ¿ÏƒÏ„Î­Î¸Î·ÎºÎµ')});
window.removeEmployee=async i=>{let name=employees[i];if(entries.some(e=>e.employee===name))return toast('Î¥Ï€Î¬ÏÏ‡Î¿Ï…Î½ ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚ Î³Î¹Î± Î±Ï…Ï„ÏŒ Ï„Î¿ Î¬Ï„Î¿Î¼Î¿');if(confirm(`ÎÎ± Î´Î¹Î±Î³ÏÎ±Ï†ÎµÎ¯ Î¿/Î· ${name};`)){let {error}=await db.from('employees').delete().eq('user_id',currentUser.id).eq('name',name);if(error)return toast('Î— Î´Î¹Î±Î³ÏÎ±Ï†Î® Î±Ï€Î­Ï„Ï…Ï‡Îµ');await loadCloudData()}};
window.deleteEntry=async id=>{if(confirm('ÎÎ± Î´Î¹Î±Î³ÏÎ±Ï†ÎµÎ¯ Î· ÎºÎ±Ï„Î±Ï‡ÏŽÏÎ¹ÏƒÎ·;')){let {error}=await db.from('entries').delete().eq('id',id);if(error)return toast('Î— Î´Î¹Î±Î³ÏÎ±Ï†Î® Î±Ï€Î­Ï„Ï…Ï‡Îµ');await loadCloudData()}};
window.editEntry=id=>{let e=entries.find(x=>x.id===id);if(!e)return;$('editId').value=e.id;$('date').value=e.work_date;$('employee').value=e.employee;$('status').value=e.status;$('start').value=e.start_time?e.start_time.slice(0,5):'';$('end').value=e.end_time?e.end_time.slice(0,5):'';$('notes').value=e.notes||'';$('formTitle').textContent='Î‘Î»Î»Î±Î³Î® ÎºÎ±Ï„Î±Ï‡ÏŽÏÎ¹ÏƒÎ·Ï‚';$('cancelEdit').hidden=false;toggleTimes();scrollTo({top:0,behavior:'smooth'})};
$('cancelEdit').onclick=resetForm;$('status').onchange=toggleTimes;$('month').onchange=renderSummary;$('summaryEmployee').onchange=renderSummary;
$('historyEmployee').onchange=()=>{historyPage=1;renderRecent()};$('historyMonth').onchange=()=>{historyPage=1;renderRecent()};$('clearHistoryFilters').onclick=()=>{$('historyEmployee').value='';$('historyMonth').value='';historyPage=1;renderRecent()};$('prevPage').onclick=()=>{if(historyPage>1){historyPage--;renderRecent()}};$('nextPage').onclick=()=>{historyPage++;renderRecent()};
$('exportExcel').onclick=()=>{let month=$('month').value,emp=$('summaryEmployee').value,list=entries.filter(e=>e.employee===emp&&e.work_date.startsWith(month)).sort((a,b)=>a.work_date.localeCompare(b.work_date));let rows=[['Î—Î¼ÎµÏÎ¿Î¼Î·Î½Î¯Î±','Î•ÏÎ³Î±Î¶ÏŒÎ¼ÎµÎ½Î¿Ï‚','ÎšÎ±Ï„Î¬ÏƒÏ„Î±ÏƒÎ·','ÎˆÎ½Î±ÏÎ¾Î·','Î›Î®Î¾Î·','ÎÏÎµÏ‚','Î Î±ÏÎ±Ï„Î·ÏÎ®ÏƒÎµÎ¹Ï‚'],...list.map(e=>[formatDate(e.work_date),e.employee,e.status,e.start_time?.slice(0,5)||'',e.end_time?.slice(0,5)||'',formatHours(hours(e)),e.notes])];let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');download(`Î Î±ÏÎ¿Ï…ÏƒÎ¹Î¿Î»ÏŒÎ³Î¹Î¿_${emp}_${month}.csv`,'text/csv;charset=utf-8',csv);toast('Î¤Î¿ Î±ÏÏ‡ÎµÎ¯Î¿ Excel Î´Î·Î¼Î¹Î¿Ï…ÏÎ³Î®Î¸Î·ÎºÎµ')};
$('exportPdf').onclick=()=>{document.title=`ÎœÎ·Î½Î¹Î±Î¯Î± Î±Î½Î±Ï†Î¿ÏÎ¬ - ${$('summaryEmployee').value} - ${$('month').value}`;window.print();setTimeout(()=>document.title='Î Î±ÏÎ¿Ï…ÏƒÎ¹Î¿Î»ÏŒÎ³Î¹Î¿ Î ÏÎ¿ÏƒÏ‰Ï€Î¹ÎºÎ¿Ï',500)};
$('backupData').onclick=()=>{let backupEntries=entries.map(e=>({id:e.id,date:e.work_date,employee:e.employee,status:e.status,start:e.start_time?.slice(0,5)||'',end:e.end_time?.slice(0,5)||'',notes:e.notes||''}));download(`Î‘Î½Ï„Î¯Î³ÏÎ±Ï†Î¿_Î Î±ÏÎ¿Ï…ÏƒÎ¹Î¿Î»Î¿Î³Î¯Î¿Ï…_${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify({version:2,createdAt:new Date().toISOString(),employees,entries:backupEntries},null,2));toast('Î¤Î¿ Î±Î½Ï„Î¯Î³ÏÎ±Ï†Î¿ Î´Î·Î¼Î¹Î¿Ï…ÏÎ³Î®Î¸Î·ÎºÎµ')};
$('restoreData').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{let data=JSON.parse(await file.text());if(!Array.isArray(data.employees)||!Array.isArray(data.entries))throw Error();if(!confirm(`Î˜Î± Ï€ÏÎ¿ÏƒÏ„ÎµÎ¸Î¿ÏÎ½ ${data.entries.length} ÎºÎ±Ï„Î±Ï‡Ï‰ÏÎ¯ÏƒÎµÎ¹Ï‚ ÏƒÏ„Î¿ cloud. Î£Ï…Î½Î­Ï‡ÎµÎ¹Î±;`))return;setSync('Î•Ï€Î±Î½Î±Ï†Î¿ÏÎ¬â€¦');if(data.employees.length){let {error}=await db.from('employees').upsert(data.employees.map(name=>({user_id:currentUser.id,name})),{onConflict:'user_id,name'});if(error)throw error}if(data.entries.length){let rows=data.entries.map((x,i)=>({id:x.id&&String(x.id).includes('-')?String(x.id):`restore-${Date.now()}-${i}`,user_id:currentUser.id,work_date:x.work_date||x.date,employee:x.employee,status:x.status,start_time:x.start_time||x.start||null,end_time:x.end_time||x.end||null,notes:x.notes||''}));let {error}=await db.from('entries').upsert(rows);if(error)throw error}await loadCloudData();toast('Î— ÎµÏ€Î±Î½Î±Ï†Î¿ÏÎ¬ Î¿Î»Î¿ÎºÎ»Î·ÏÏŽÎ¸Î·ÎºÎµ')}catch(err){alert('Î¤Î¿ Î±ÏÏ‡ÎµÎ¯Î¿ Î´ÎµÎ½ Î®Ï„Î±Î½ Î­Î³ÎºÏ…ÏÎ¿ Î® Î· ÎµÏ€Î±Î½Î±Ï†Î¿ÏÎ¬ Î±Ï€Î­Ï„Ï…Ï‡Îµ.')}finally{e.target.value=''}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');if(b.dataset.page==='summary')renderSummary()});

(async()=>{toggleTimes();let {data:{session}}=await db.auth.getSession();if(session?.user)await enterApp(session.user);else showApp(false)})();

